---
version: '2'

services:
  mailman-core:
    image: maxking/mailman-core:${MAILMAN_IMAGE_VERSION}
    restart: always
    stop_grace_period: 30s
    hostname: mailman-core
    depends_on:
    - database
    links:
    - database:database
    volumes:
    - /opt/mailman/core:/opt/mailman/
    environment:
    - DATABASE_URL=postgres://mailman:${DATABASE_PASSWORD}@database/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    - HYPERKITTY_API_KEY=${HYPERKITTY_API_KEY}
    ports:
    - "127.0.0.1:8001:8001" # API
    - "127.0.0.1:8024:8024" # LMTP - incoming emails
    networks:
      mailman:

  mailman-web:
    image: maxking/mailman-web:${MAILMAN_IMAGE_VERSION}
    restart: always
    hostname: mailman-web
    depends_on:
    - database
    links:
    - mailman-core:mailman-core
    - database:database
    volumes:
    - /opt/mailman/web:/opt/mailman-web-data
    environment:
    - DATABASE_TYPE=postgres
    - DATABASE_URL=postgres://mailman:${DATABASE_PASSWORD}@database/mailmandb
    - HYPERKITTY_API_KEY=${HYPERKITTY_API_KEY}
    - MAILMAN_ADMIN_EMAIL=${MAILMAN_ADMIN_EMAIL}
    - MAILMAN_ADMIN_USER=${MAILMAN_ADMIN_USER}
    - SECRET_KEY=${DJANGO_SECRET_KEY}
    - SERVE_FROM_DOMAIN=${SERVE_FROM_DOMAIN}
    - SMTP_HOST=${SMTP_HOST}
    - SMTP_PORT=${SMTP_PORT}
    - SMTP_HOST_USER=${SMTP_HOST_USER}
    - SMTP_HOST_PASSWORD=${SMTP_HOST_PASSWORD}
    - SMTP_USE_TLS=${SMTP_USE_TLS}
    ports:
    - "127.0.0.1:8000:8000" # HTTP
    - "127.0.0.1:8080:8080" # uwsgi
    networks:
      mailman:

  database:
    image: postgres:9.6-alpine
    restart: always
    volumes:
    - /opt/mailman/database:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=mailmandb
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    - POSTGRES_USER=mailman
    networks:
      mailman:

networks:
   mailman:
     driver: bridge
     ipam:
       driver: default
       config:
       - subnet: 172.19.199.0/24
