---
version: '2'

services:
  mailman-core:
    image: maxking/mailman-core:0.3
    hostname: mailman-core
    stop_grace_period: 30s
    depends_on:
    - database
    links:
    - database:database
    volumes:
    - /opt/mailman/core:/opt/mailman/
    environment:
    - DATABASE_URL=postgres://mailman:${DATABASE_PASSWORD}@database/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    - HYPERKITTY_API_KEY=${HYPERKITTY_API_KEY}
    networks:
      mailman:
        ipv4_address: 172.19.199.2

  mailman-web:
    image: maxking/mailman-web:0.3
    hostname: mailman-web
    depends_on:
    - database
    links:
    - mailman-core:mailman-core
    - database:database
    volumes:
    - /opt/mailman/web:/opt/mailman-web-data
    environment:
    - DATABASE_TYPE=postgres
    - DATABASE_URL=postgres://mailman:${DATABASE_PASSWORD}@database/mailmandb
    - HYPERKITTY_API_KEY=${HYPERKITTY_API_KEY}
    - MAILMAN_ADMIN_EMAIL=${MAILMAN_ADMIN_EMAIL}
    - MAILMAN_ADMIN_USER=${MAILMAN_ADMIN_USER}
    - SECRET_KEY=${DJANGO_SECRET_KEY}
    - SERVE_FROM_DOMAIN=${SERVE_FROM_DOMAIN}
    - SMTP_HOST=${SMTP_HOST}
    - SMTP_PORT=${SMTP_PORT}
    - SMTP_HOST_USER=${SMTP_HOST_USER}
    - SMTP_HOST_PASSWORD=${SMTP_HOST_PASSWORD}
    - SMTP_USE_TLS=${SMTP_USE_TLS}
    networks:
      mailman:
        ipv4_address: 172.19.199.3

  database:
    image: postgres:9.6-alpine
    volumes:
    - /opt/mailman/database:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=mailmandb
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    - POSTGRES_USER=mailman
    networks:
      mailman:
        ipv4_address: 172.19.199.4

networks:
   mailman:
     driver: bridge
     ipam:
       driver: default
       config:
       - subnet: 172.19.199.0/24
